apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:
  rbac:
    policy: |-
      g, cluster-admins, role:admin
      g, admin, role:admin
      g, system:cluster-admins, role:admin
    scopes: '[groups,email]'