apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-config-project.yaml
  - gitops-config-project.yaml
  - operators-config-project.yaml

# Add a patch to ignore the tracking ID on the ArgoCD resource
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ArgoCD
      name: openshift-gitops
      namespace: openshift-gitops
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1compare-options
        value: IgnoreExtraneous